add_executable(polyline_simplification test/polyline_simplification/polyline_simplification_test.cpp src/polyline_simplification/polyline_simplification.cpp)
target_include_directories(polyline_simplification PUBLIC ${JSONCPP_INCLUDE_DIRS} ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(polyline_simplification ${JSONCPP_LIBRARIES})